<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_get_article' => [['articleId'], ['_controller' => 'App\\Controller\\Api\\ArticleApiController::getArticle'], [], [['variable', '/', '[^/]++', 'articleId', true], ['text', '/api/article']], [], [], []],
    'api_get_article_comments' => [['articleId'], ['_controller' => 'App\\Controller\\Api\\CommentApiController::getArticleComments'], [], [['text', '/comment'], ['variable', '/', '[^/]++', 'articleId', true], ['text', '/api/article']], [], [], []],
    'api_get_comment_answers' => [['commentId'], ['_controller' => 'App\\Controller\\Api\\CommentApiController::getCommentAnswers'], [], [['text', '/answer'], ['variable', '/', '[^/]++', 'commentId', true], ['text', '/api/comment']], [], [], []],
    'api_create_comment' => [['articleId'], ['_controller' => 'App\\Controller\\Api\\CommentApiController::createComment'], [], [['text', '/comment'], ['variable', '/', '[^/]++', 'articleId', true], ['text', '/api/article']], [], [], []],
    'api_create_answer' => [['commentId'], ['_controller' => 'App\\Controller\\Api\\CommentApiController::createAnswer'], [], [['text', '/answer'], ['variable', '/', '[^/]++', 'commentId', true], ['text', '/api/comment']], [], [], []],
    'api_rate_comment' => [['commentId'], ['_controller' => 'App\\Controller\\Api\\CommentApiController::rateComment'], [], [['text', '/rate'], ['variable', '/', '[^/]++', 'commentId', true], ['text', '/api/comment']], [], [], []],
    'connect_facebook_start' => [[], ['_controller' => 'App\\Controller\\Auth\\FacebookController::facebookConnectAction'], [], [['text', '/connect/facebook']], [], [], []],
    'connect_facebook_check' => [[], ['_controller' => 'App\\Controller\\Auth\\FacebookController::facebookConnectCheckAction'], [], [['text', '/connect/facebook/check']], [], [], []],
    'connect_google_start' => [[], ['_controller' => 'App\\Controller\\Auth\\GoogleController::googleConnectAction'], [], [['text', '/connect/google']], [], [], []],
    'connect_google_check' => [[], ['_controller' => 'App\\Controller\\Auth\\GoogleController::connectCheckAction'], [], [['text', '/connect/google/check']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\Site\\BlogController::listArticlesAction'], [], [['text', '/']], [], [], []],
    'article_view' => [['articleId'], ['_controller' => 'App\\Controller\\Site\\BlogController::viewArticleAction'], [], [['variable', '/', '[^/]++', 'articleId', true], ['text', '/article']], [], [], []],
];
