<?php

namespace ContainerOkR4rQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Auth\GoogleController' shared autowired service.
     *
     * @return \App\Controller\Auth\GoogleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Auth/GoogleController.php';

        $container->services['App\\Controller\\Auth\\GoogleController'] = $instance = new \App\Controller\Auth\GoogleController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\Auth\\GoogleController', $container));

        return $instance;
    }
}
