<?php

namespace ContainerOkR4rQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Command/DebugFirewallCommand.php';

        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.amOfXIr'] ?? $container->get_ServiceLocator_AmOfXIrService()), ($container->privates['.service_locator.TQdqbzL'] ?? $container->load('get_ServiceLocator_TQdqbzLService')), ['api' => [0 => ($container->privates['App\\Security\\ApiAuthenticator'] ?? $container->load('getApiAuthenticatorService'))], 'public' => [0 => ($container->privates['App\\Security\\GoogleAuthenticator'] ?? $container->load('getGoogleAuthenticatorService')), 1 => ($container->privates['App\\Security\\FacebookAuthenticator'] ?? $container->load('getFacebookAuthenticatorService'))]], false);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
