<?php

namespace ContainerT2lO8cm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UMNmJWuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uMNmJWu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uMNmJWu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentService' => ['privates', 'App\\Service\\CommentService', 'getCommentServiceService', true],
            'commentsRatesService' => ['privates', 'App\\Service\\CommentsRatesService', 'getCommentsRatesServiceService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'commentService' => 'App\\Service\\CommentService',
            'commentsRatesService' => 'App\\Service\\CommentsRatesService',
            'security' => '?',
        ]);
    }
}
