<?php

namespace ContainerT2lO8cm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\ArticleApiController::getArticle' => ['privates', '.service_locator.o4XLqj.', 'get_ServiceLocator_O4XLqj_Service', true],
            'App\\Controller\\Api\\CommentApiController::createAnswer' => ['privates', '.service_locator.EbTfwDn', 'get_ServiceLocator_EbTfwDnService', true],
            'App\\Controller\\Api\\CommentApiController::createComment' => ['privates', '.service_locator.6rrIHwI', 'get_ServiceLocator_6rrIHwIService', true],
            'App\\Controller\\Api\\CommentApiController::getArticleComments' => ['privates', '.service_locator.m3hEUyd', 'get_ServiceLocator_M3hEUydService', true],
            'App\\Controller\\Api\\CommentApiController::getCommentAnswers' => ['privates', '.service_locator.m3hEUyd', 'get_ServiceLocator_M3hEUydService', true],
            'App\\Controller\\Api\\CommentApiController::rateComment' => ['privates', '.service_locator.uMNmJWu', 'get_ServiceLocator_UMNmJWuService', true],
            'App\\Controller\\Auth\\FacebookController::facebookConnectAction' => ['privates', '.service_locator.hokdgZZ', 'get_ServiceLocator_HokdgZZService', true],
            'App\\Controller\\Auth\\FacebookController::facebookConnectCheckAction' => ['privates', '.service_locator.6KSh6Cj', 'get_ServiceLocator_6KSh6CjService', true],
            'App\\Controller\\Auth\\GoogleController::connectCheckAction' => ['privates', '.service_locator.6KSh6Cj', 'get_ServiceLocator_6KSh6CjService', true],
            'App\\Controller\\Auth\\GoogleController::googleConnectAction' => ['privates', '.service_locator.hokdgZZ', 'get_ServiceLocator_HokdgZZService', true],
            'App\\Controller\\Site\\BlogController::listArticlesAction' => ['privates', '.service_locator.o4XLqj.', 'get_ServiceLocator_O4XLqj_Service', true],
            'App\\Controller\\Site\\BlogController::viewArticleAction' => ['privates', '.service_locator.l.CnW1L', 'get_ServiceLocator_L_CnW1LService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Api\\ArticleApiController:getArticle' => ['privates', '.service_locator.o4XLqj.', 'get_ServiceLocator_O4XLqj_Service', true],
            'App\\Controller\\Api\\CommentApiController:createAnswer' => ['privates', '.service_locator.EbTfwDn', 'get_ServiceLocator_EbTfwDnService', true],
            'App\\Controller\\Api\\CommentApiController:createComment' => ['privates', '.service_locator.6rrIHwI', 'get_ServiceLocator_6rrIHwIService', true],
            'App\\Controller\\Api\\CommentApiController:getArticleComments' => ['privates', '.service_locator.m3hEUyd', 'get_ServiceLocator_M3hEUydService', true],
            'App\\Controller\\Api\\CommentApiController:getCommentAnswers' => ['privates', '.service_locator.m3hEUyd', 'get_ServiceLocator_M3hEUydService', true],
            'App\\Controller\\Api\\CommentApiController:rateComment' => ['privates', '.service_locator.uMNmJWu', 'get_ServiceLocator_UMNmJWuService', true],
            'App\\Controller\\Auth\\FacebookController:facebookConnectAction' => ['privates', '.service_locator.hokdgZZ', 'get_ServiceLocator_HokdgZZService', true],
            'App\\Controller\\Auth\\FacebookController:facebookConnectCheckAction' => ['privates', '.service_locator.6KSh6Cj', 'get_ServiceLocator_6KSh6CjService', true],
            'App\\Controller\\Auth\\GoogleController:connectCheckAction' => ['privates', '.service_locator.6KSh6Cj', 'get_ServiceLocator_6KSh6CjService', true],
            'App\\Controller\\Auth\\GoogleController:googleConnectAction' => ['privates', '.service_locator.hokdgZZ', 'get_ServiceLocator_HokdgZZService', true],
            'App\\Controller\\Site\\BlogController:listArticlesAction' => ['privates', '.service_locator.o4XLqj.', 'get_ServiceLocator_O4XLqj_Service', true],
            'App\\Controller\\Site\\BlogController:viewArticleAction' => ['privates', '.service_locator.l.CnW1L', 'get_ServiceLocator_L_CnW1LService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Api\\ArticleApiController::getArticle' => '?',
            'App\\Controller\\Api\\CommentApiController::createAnswer' => '?',
            'App\\Controller\\Api\\CommentApiController::createComment' => '?',
            'App\\Controller\\Api\\CommentApiController::getArticleComments' => '?',
            'App\\Controller\\Api\\CommentApiController::getCommentAnswers' => '?',
            'App\\Controller\\Api\\CommentApiController::rateComment' => '?',
            'App\\Controller\\Auth\\FacebookController::facebookConnectAction' => '?',
            'App\\Controller\\Auth\\FacebookController::facebookConnectCheckAction' => '?',
            'App\\Controller\\Auth\\GoogleController::connectCheckAction' => '?',
            'App\\Controller\\Auth\\GoogleController::googleConnectAction' => '?',
            'App\\Controller\\Site\\BlogController::listArticlesAction' => '?',
            'App\\Controller\\Site\\BlogController::viewArticleAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Api\\ArticleApiController:getArticle' => '?',
            'App\\Controller\\Api\\CommentApiController:createAnswer' => '?',
            'App\\Controller\\Api\\CommentApiController:createComment' => '?',
            'App\\Controller\\Api\\CommentApiController:getArticleComments' => '?',
            'App\\Controller\\Api\\CommentApiController:getCommentAnswers' => '?',
            'App\\Controller\\Api\\CommentApiController:rateComment' => '?',
            'App\\Controller\\Auth\\FacebookController:facebookConnectAction' => '?',
            'App\\Controller\\Auth\\FacebookController:facebookConnectCheckAction' => '?',
            'App\\Controller\\Auth\\GoogleController:connectCheckAction' => '?',
            'App\\Controller\\Auth\\GoogleController:googleConnectAction' => '?',
            'App\\Controller\\Site\\BlogController:listArticlesAction' => '?',
            'App\\Controller\\Site\\BlogController:viewArticleAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
