<?php

namespace ContainerT2lO8cm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentsRatesServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommentsRatesService' shared autowired service.
     *
     * @return \App\Service\CommentsRatesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CommentsRatesService.php';

        return $container->privates['App\\Service\\CommentsRatesService'] = new \App\Service\CommentsRatesService(($container->privates['App\\Repository\\CommentsRatesRepository'] ?? $container->load('getCommentsRatesRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
