<?php

namespace ContainerT2lO8cm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpu_Oauth2_Client_FacebookMainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'knpu.oauth2.client.facebook_main' shared service.
     *
     * @return \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/Provider/FacebookClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-client/src/Tool/ArrayAccessorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-client/src/Tool/GuardedPropertyTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-client/src/Provider/AbstractProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-facebook/src/Provider/Facebook.php';

        return $container->services['knpu.oauth2.client.facebook_main'] = new \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient(($container->privates['knpu.oauth2.provider_factory'] ?? $container->load('getKnpu_Oauth2_ProviderFactoryService'))->createProvider('League\\OAuth2\\Client\\Provider\\Facebook', ['clientId' => $container->getEnv('OAUTH_FACEBOOK_ID'), 'clientSecret' => $container->getEnv('OAUTH_FACEBOOK_SECRET'), 'graphApiVersion' => 'v2.12'], 'connect_facebook_check', [], []), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
